// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2084.CMonster2017.subsystems;

import org.usfirst.frc2084.CMonster2017.RobotMap;
import org.usfirst.frc2084.CMonster2017.commands.*;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class IntakeBase extends Subsystem {
	
	//currently unused subsystem
	

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid inOutSolenoid = RobotMap.intakeBaseInOutSolenoid;
    private final DoubleSolenoid gateSolenoid = RobotMap.intakeBasegateSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

	public void IntakeCommands(){
		
	}
	
	//these methods are called into the button commands
	//make the pistons go in and out
	public void ballsgoIn(){
		inOutSolenoid.set(DoubleSolenoid.Value.kForward);
	}
	
	public void ballsgoOut(){
		inOutSolenoid.set(DoubleSolenoid.Value.kReverse);
		
	}
	
	public void openGate(){
		gateSolenoid.set(DoubleSolenoid.Value.kForward);
	}
	
	public void closeGate(){
		gateSolenoid.set(DoubleSolenoid.Value.kReverse);
	}
	
	
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

