// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2084.CMonster2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.smartdashboard.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveBaseLeftTalon1;
    public static Encoder driveBaseLeftEncoder;
    public static PIDController driveBaseLeftPIDController1;
    public static SpeedController driveBaseRightTanlon1;
    public static Encoder driveBaseRightEncoder;
    public static PIDController driveBaseRightPIDController1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseLeftTalon1 = new Talon(0);
        LiveWindow.addActuator("DriveBase", "LeftTalon1", (Talon) driveBaseLeftTalon1);
        
        driveBaseLeftEncoder = new Encoder(19, 20, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveBase", "LeftEncoder", driveBaseLeftEncoder);
        driveBaseLeftEncoder.setDistancePerPulse(1.0);
        driveBaseLeftEncoder.setPIDSourceType(PIDSourceType.kRate);
        driveBaseLeftPIDController1 = new PIDController(0.1, 0.0, 0.0, 0.0, driveBaseLeftEncoder, driveBaseLeftTalon1, 0.02);
        LiveWindow.addActuator("DriveBase", "LeftPIDController1", driveBaseLeftPIDController1);
        driveBaseLeftPIDController1.setContinuous(false);
        driveBaseLeftPIDController1.setAbsoluteTolerance(0.2);

        driveBaseLeftPIDController1.setInputRange(-1.0, 1.0);
        driveBaseLeftPIDController1.setOutputRange(-1.0, 1.0);
        driveBaseRightTanlon1 = new Talon(3);
        LiveWindow.addActuator("DriveBase", "RightTanlon1", (Talon) driveBaseRightTanlon1);
        
        driveBaseRightEncoder = new Encoder(22, 23, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveBase", "RightEncoder", driveBaseRightEncoder);
        driveBaseRightEncoder.setDistancePerPulse(1.0);
        driveBaseRightEncoder.setPIDSourceType(PIDSourceType.kRate);
        driveBaseRightPIDController1 = new PIDController(0.1, 0.0, 0.0, 0.0, driveBaseRightEncoder, driveBaseRightTanlon1, 0.02);
        LiveWindow.addActuator("DriveBase", "RightPIDController1", driveBaseRightPIDController1);
        driveBaseRightPIDController1.setContinuous(false);
        driveBaseRightPIDController1.setAbsoluteTolerance(0.2);

        driveBaseRightPIDController1.setInputRange(-1.0, 1.0);
        driveBaseRightPIDController1.setOutputRange(-1.0, 1.0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
